"""Render docs/feature_dictionary.md from the code schema plus measured stats.

Example:
    python scripts/write_feature_dictionary.py \
        --report data/work/p3/features.report.json \
        --quality data/work/p3/features.quality.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from business_entity_resolution.similarity_features import (
    CONTEXT_FEATURE_SCHEMA, FEATURE_DESCRIPTIONS, FEATURE_VERSION, PAIR_FEATURE_SCHEMA,
    RETRIEVAL_FEATURE_SCHEMA,
)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--report", type=Path)
    parser.add_argument("--quality", type=Path)
    parser.add_argument("--output", type=Path, default=Path("docs/feature_dictionary.md"))
    args = parser.parse_args()
    report = json.loads(args.report.read_text())["features"] if args.report else {}
    quality = json.loads(args.quality.read_text()) if args.quality else {}
    auc = quality.get("univariate_auc", {})
    perm = quality.get("permutation_importance_ap_drop", {})
    lines = [
        f"# Pair feature dictionary ({FEATURE_VERSION})",
        "",
        "Generated by `scripts/write_feature_dictionary.py` from `similarity_features.py`. "
        "Missing rate, univariate AUC (max(AUC, 1-AUC)) and permutation importance "
        "(drop in average precision) are measured on the Day 1 dev pairs "
        "(20k S1, ~975k retrieved pairs). Column order is part of the contract.",
        "",
    ]
    for title, schema in (
        ("Pair features (`calculate_pair_features`)", PAIR_FEATURE_SCHEMA),
        ("Context features (`add_context_features`, run on the full table)", CONTEXT_FEATURE_SCHEMA),
        ("Retrieval features (`add_retrieval_features`, optional)", RETRIEVAL_FEATURE_SCHEMA),
    ):
        lines += [f"## {title}", "", "| # | Feature | dtype | Missing | AUC | Perm. imp. | Meaning |",
                  "|---|---|---|---|---|---|---|"]
        for i, (name, dtype) in enumerate(schema.items(), 1):
            miss = report.get(name, {}).get("missing_rate")
            lines.append(
                f"| {i} | `{name}` | {dtype} | "
                f"{'' if miss is None else f'{miss:.2%}'} | {auc.get(name, '')} | "
                f"{perm.get(name, '')} | {FEATURE_DESCRIPTIONS[name]} |"
            )
        lines.append("")
    args.output.write_text("\n".join(lines))
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
